import os

SECRET_KEY = os.getenv("FLASK_SECRET_KEY")
DEBUG = os.getenv("FLASK_DEBUG")
ENV = os.getenv("FLASK_ENV")
APP = os.getenv("FLASK_APP")
PORT = os.getenv("FLASK_PORT")
SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI')
SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv('SQLALCHEMY_TRACK_MODIFICATIONS')

RQ_DASHBOARD_REDIS_URL = os.getenv("RQ_DASHBOARD_REDIS_URL")
